# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_pXe9h2m0o9KkS0pgJC0X2bGUeuTZYt

#Exploratory Data Analysis of Point in Time Estimates of Homelessness in the US

# Introduction:

 Estimates of homelessness at a single point in time (PIT) by state. Data compiled from HUD's Annual Homeless Assessment Report (AHAR) findings. "The Annual Homeless Assessment Report (AHAR) is a HUD report to the United States Congress that provides nationwide estimates of homelessness, including demographic characteristics of homeless people, service use patterns, and the capacity to house homeless people," according to HUD.

**Import Necessary Data from Numpy, Pandas, Matplotlib, and Seaborn.**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

"""**Import the data set from the offical site**

* After importing the dataset we are using some functions like '.info','.head','describe', to get the size, no of coulumns,rows,names and data types.

"""

# import the csv file 
hl = pd.read_csv("https://storage.googleapis.com/hi6066/Point_in_Time_Estimates_of_Homelessness_in_the_US_by_State%20(2).csv")

#it gives you first couple of records od data
hl.head()

"""## pivot table create a spreadsheet-style pivot table as a DataFrame."""

pivot = pd.pivot_table(hl, index =['year', 'state','count_type','count'])
pivot

"""## shape gives you the count of records in the form of rows and cols"""

print(hl.shape)

"""##  We use .info method to Understand the number and names of columns, column data types, the number of null values in the data."""

hl.info()

"""* Using the.describe function is another excellent way to gain a better understanding of the data. This function generates statistical information such as standard deviations, count, mean, maximum, and percentiles"""

hl.describe().T

"""## DATA CLEANING

* The first step in data cleaning is to rempove spaces from headers.
"""

hl.columns = hl.columns.str.replace(' ','_')
hl.head()

"""## Nunique() function get the unique values from specific column without repeatation."""

hl.state.nunique()

"""## Here we are converting the each col header to lower case."""

hl.columns = hl.columns.str.lower()
hl.head(3)

"""## drop duplicates() method aids in the removal of duplicates from Pandas Dataframes."""

hl =hl.drop_duplicates()
hl.reset_index(drop=True, inplace = True)

"""## dropna() funaction helps to drop the Null values from Dataset"""

hl1 = hl.dropna()
hl1.isnull()
hl1

""" ## Here we are dropping the total value from state columns."""

hl2 =hl1.drop(hl1[(hl['state']== 'Total')].index, inplace=False)
hl2
for col in hl2:
  print(hl2[col].unique())

"""# Opertions on Dataset

* To get the top n sorted rows on a column, use the nlargest function and specify the column name to sort on. To obtain the top five entries in the data.
"""

hl2.nlargest(5,"count" ,keep="first")

"""* The function value_counts returns the frequency counts in descending order."""

hl2['count_type'].value_counts()

"""The above statement show that there are 10 diferent type of homeless people categories."""

hl.nlargest(5,'year')

hl.nsmallest(5,'year')

"""## plots

## 1) Barplot

The first plot is to show No of homeless people states wise in United States.
"""

plt1 = hl2[['state','count']].head(20)
plt1.plot.bar(x='state')
plt.title("No of homeless people by state wise")
plt.xlabel("state")
plt.ylabel("count of people")
plt.show()

""" ###  Here we are craeting a new df which holds the data for overall homeless people in 2018 only"""

overall2018 = hl2[(hl2.year == 2018)& (hl2.count_type=='Overall Homeless')]
print(overall2018)

"""##2) Scatter plot 

Now, we can plot the sactter polt of overall homeless people in 2018.

"""

fig = plt.figure(figsize =(15, 10))
plt.scatter(x= overall2018['state'],y=overall2018['count'])
plt.title('NO of Overall homeless people in 2018')
plt.xlabel("state")
plt.ylabel("No of people")
plt.xticks(rotation=90)
plt.figure(figsize= (80,80))
plt.show()

"""### The above scatter graph shows that the CA state has highest no of homeless people

## 3) Histogram
"""

plt.figure(figsize=(80,10))
plt1 = hl2[['state','count']]
plt1.plot(x='state')
plt.title("No of homeless people by state wise")
plt.xlabel("state")
plt.ylabel("count of people")
plt.show()

"""### The above graph shows the count of homeless people state wise

## 4) Geospatial Diagrams
"""

from urllib.request import urlopen
import json
import plotly.express as px


fig = px.choropleth(overall2018, locations='state', locationmode="USA-states", color='count',
                             scope="usa",
                             labels={'count':'overall homeless'})
fig.show()

"""### The above graph shows that the California state has highest number of overall homeless people about 129.97k

#5) Bar graph

### here,will get the data for highest no of homeless people for MI state in 2018
"""

overall_MI_2018 = hl2[(hl2.state == 'MI')& (hl2.year == 2018)]
overall_MI_2018_max=overall_MI_2018.nlargest(20, 'count')
overall_MI_2018

hl3 =overall_MI_2018_max['count_type']
count = overall_MI_2018_max['count']
fig = plt.figure(figsize =(50, 20))
plt.bar(hl3, count)
plt.xlabel("Categories of Homelessness people")
plt.ylabel("Number of homeless people")
plt.title("No of homeless people in MI in 2018")
plt.xticks(rotation=90)
plt.show()

"""## The above graph is showing the number of homeless people in Michigan state in year of 2018

## 6) Heat map
"""

hl4 = hl2.pivot_table(index=['year'],columns=['count_type'])
corr = pd.DataFrame(hl4).corr()
sns.heatmap(corr, vmin=-1, vmax=1,center=0, cmap=sns.diverging_palette(200,20, n=100))
corr

"""The above graph is showing the  correlation between count and count_type, we can see the Homeless Children of Parenting Youth has negative corrleation and chronically homelss has positive correlation.

## 7) Pie plot
"""

from numpy.ma import right_shift
hl5 = hl1[['state','count']].sort_values(['count'],ascending=True).groupby('state',as_index = False).sum().head()
hl5
plt.pie(hl5['count'],labels = hl5['state'],radius=2,autopct='%.0f%%',
                                          textprops={'size': 'smaller'})
plt.legend(title='state')
plt.show()

"""The above pie chart shows the sum of top five states which has highest no of homeless people.

# Conclusion

1. The highest overall homeless people in all states is from california. The second highest is New york. The third highest is from florida state.

2. If we only consider the total number of homeless people in 2018, California has the highest nuumber of homeless people.

3. If we only look at the number of homeless people in Detroit in 2018, the overall homeless people have the highest number, followed by the sheltered total homeless and the sheltered ES homeless people.

4. If we plot the correlation between count and count_type, we can see the Homeless Children of Parenting Youth has negative corrleation and chronically homelss has positive correlation.

5. If we get the sum of count of top five states of homeless people are as follws:
CA,AZ,AL,AR,AK.
"""